name: Build library

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # чтобы теги подтянулись

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Extract version from build.gradle.kts
        id: version
        run: |
          VERSION=$(grep "^version\s*=" build.gradle.kts | sed 's/.*"\(.*\)".*/\1/')
          echo "Parsed version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        run: |
          TAG="v${{ steps.version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping release."
            exit 0
          fi

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Git Tag
        run: |
          TAG="v${{ steps.version.outputs.version }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          generate_release_notes: true
